### ISSUE TITLE
Building with `elm-optimize-level-2`

### ISSUE THREAD

**Issue by MattiaVerticchio** [lindsaykwardell/vite-elm-spa#2]
Hi and thanks for publishing this template! 😁

I’d like to use `elm-optimize-level-2` in the building process, is there a way to add it to the template?

**Comment by clojj** [comment]
Hi, that should probably be an issue/request here:
https://github.com/hmsk/vite-plugin-elm
...but reading about that here https://github.com/mdgriffith/elm-optimize-level-2 (I ddn't know this project)
I'd be cautious about it's stability (?)

**Comment by MattiaVerticchio** [comment]
Thanks, @clojj, I’ll take a look at the plugin repo 😁
